site_name: FlowRedux
site_url: https://freeletics.github.io/FlowRedux/
repo_name: FlowRedux
repo_url: https://github.com/freeletics/FlowRedux
site_description: "Kotlin Multiplatform library to create state machines"
site_author: Freeletics

copyright: 'Copyright &copy; 2023 Freeletics.'

theme:
  name: 'material'
  favicon: images/icon-freeletics.svg
  logo: images/logo-freeletics.svg
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - toc.integrate

nav:
  - 'Getting Started': index.md
  - 'User Guide':
    - 'State and Action': user-guide/1_basics.md
    - 'inState block': user-guide/2_inState.md
    - 'onEnter block': user-guide/3_onEnter.md
    - 'State and ChangedState': user-guide/4_State-ChangedState.md
    - 'onAction block': user-guide/5_onAction.md
    - 'collectWhileInState block': user-guide/6_collectWhileInState.md
    - 'Effects': user-guide/7_effects.md
    - 'Condition block': user-guide/8_condition.md
    - 'untilIdentityChanged block': user-guide/9_untilIdentityChanged.md
    - 'Acting across multiple states': user-guide/10_accross-multiple-states.md
    - 'ExecutionPolicy': user-guide/11_ExecutionPolicy.md
    - 'Improve readability': user-guide/12_improve-readability.md
    - 'Composing statemachines': user-guide/13_composing-statemachines.md
    - 'Writing test': user-guide/14_testing.md
  - 'DSL-Cheatsheet': dsl-cheatsheet.md
  - 'Compose': compose.md
  - 'API':
    - 'DSL': API/dsl
    - 'Compose': API/compose
  - 'Contributing': contributing.md
  - 'Changelog': changelog.md

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
