site_name: FlowRedux
site_url: https://freeletics.github.io/FlowRedux/
repo_name: FlowRedux
repo_url: https://github.com/freeletics/FlowRedux
site_description: "Kotlin Multiplatform library to create state machines"
site_author: Freeletics

copyright: 'Copyright &copy; 2020 Freeletics.'

theme:
  name: 'material'
  favicon: images/icon-freeletics.svg
  logo: images/logo-freeletics.svg
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - toc.integrate

nav:
  - 'Overview':
    - 'Getting Started': index.md
    - 'User Guide': user-guide/README.md
    - 'DSL-Cheatsheet': dsl-cheatsheet.md
    - 'Multiplatform': multiplatform.md
    - 'Compose': compose.md
    - 'API':
      - 'DSL': API/dsl
      - 'Compose': API/compose
  - 'Contributing': contributing.md
  - 'Changelog': changelog.md

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
