[versions]
kotlin = "1.7.10"
coroutines = "1.6.4"

java = "1.8"

android-gradle = "7.3.0"
android-min = "21"
android-target = "33"
android-compile = "33"
androidx-activity = "1.6.1"
androidx-appcompat = "1.5.1"
androidx-compose-compiler = "1.3.0"
androidx-compose-runtime = "1.3.0"
androidx-constraintlayout = "2.1.4"
androidx-lifecycle = "2.5.1"
androidx-fragment = "1.5.2"
androidx-recyclerview = "1.2.1"

material = "1.6.1"
adapterdelegates = "4.3.2"
timber = "5.0.1"

mad = "0.7.2"

turbine = "0.7.0"

publish = "0.22.0"
dokka = "1.7.10"
codesync = "0.2"
binarycompatibility = "0.12.1"
dependency-analysis = "1.13.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-runtime" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-runtime" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "androidx-lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

material = { module = "com.google.android.material:material", version.ref = "material" }
adapterdelegates = { module = "com.hannesdorfmann:adapterdelegates4", version.ref = "adapterdelegates" }
adapterdelegates-dsl = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version.ref = "adapterdelegates" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

mad-statemachine = { module = "com.freeletics.mad:state-machine", version.ref = "mad" }
        
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
publish-root = { id = "com.vanniktech.maven.publish.root", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
codesync = { id = "co.touchlab.kotlinxcodesync", version.ref = "codesync" }
binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binarycompatibility" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
