[versions]
kotlin = "2.2.10"
coroutines = "1.10.2"

java-target = "11"
java-toolchain = "24"

android-gradle = "8.13.0"
android-min = "21"
android-target = "36"
android-compile = "36"

androidx-compose-runtime = "1.9.0"
androidx-compose-ui = "1.9.0"
androidx-compose-foundation = "1.9.0"
androidx-compose-material = "1.9.0"
androidx-compose-material3 = "1.3.2"
jetbrains-compose = "1.8.2"

androidx-activity = "1.10.1"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
androidx-core = "1.16.0"
androidx-lifecycle = "2.9.3"
androidx-recyclerview = "1.4.0"

material = "1.13.0"
adapterdelegates = "4.3.2"
timber = "5.0.1"

turbine = "1.2.1"
kotlinx-collections-immutable= "0.4.0"

fgp = "0.32.0"
publish = "0.34.0"
dokka = "2.0.0"
binarycompatibility = "0.18.1"
dependency-analysis = "3.0.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }

androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "androidx-lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

material = { module = "com.google.android.material:material", version.ref = "material" }
adapterdelegates = { module = "com.hannesdorfmann:adapterdelegates4", version.ref = "adapterdelegates" }
adapterdelegates-dsl = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version.ref = "adapterdelegates" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

statemachine = { module = "com.freeletics.khonshu:state-machine", version = "0.32.0" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

[plugins]
fgp-android = { id = "com.freeletics.gradle.android", version.ref = "fgp" }
fgp-android-app = { id = "com.freeletics.gradle.android.app", version.ref = "fgp" }
fgp-jvm = { id = "com.freeletics.gradle.jvm", version.ref = "fgp" }
fgp-multiplatform = { id = "com.freeletics.gradle.multiplatform", version.ref = "fgp" }
fgp-publish = { id = "com.freeletics.gradle.publish.oss", version.ref = "fgp" }
fgp-root = { id = "com.freeletics.gradle.root", version.ref = "fgp" }
fgp-settings = { id = "com.freeletics.gradle.settings", version.ref = "fgp" }

android-app = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binarycompatibility" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
